-- SQL to insert all players from player_registrations.csv
-- Run this in Supabase SQL Editor after creating the players table

INSERT INTO players (player_id, player_name, status) VALUES
  ('P001', 'Lakshank Furiya', 'available'),
  ('P002', 'Kaushik yamber', 'available'),
  ('P003', 'Krishang bhardwaj', 'available'),
  ('P004', 'Aryan Singh(101)', 'available'),
  ('P005', 'Ashish R Pandey', 'available'),
  ('P006', 'Abhishek seth', 'available'),
  ('P007', 'Mitesh Mistry', 'available'),
  ('P008', 'Rupesh singh', 'available'),
  ('P009', 'Adi rane', 'available'),
  ('P010', 'Pratyush prakash kadam', 'available'),
  ('P011', 'Jatin', 'available'),
  ('P012', 'Nilesh Vishwakarma', 'available'),
  ('P013', 'Harish Jetli', 'available'),
  ('P014', 'Nikunj toshniwal', 'available'),
  ('P015', 'Parth Doshi', 'available'),
  ('P016', 'Mihir Makwana', 'available'),
  ('P017', 'Bharat miatry', 'available'),
  ('P018', 'Kishore', 'available'),
  ('P019', 'Aaryan mistry', 'available'),
  ('P020', 'Naveen Porwal', 'available'),
  ('P021', 'Prateek Gond', 'available'),
  ('P022', 'Hait Dama', 'available'),
  ('P023', 'Jay patel', 'available'),
  ('P024', 'Monish Shastri', 'available'),
  ('P025', 'Pramod Rane', 'available'),
  ('P026', 'SUNIL BOHRA', 'available'),
  ('P027', 'Viraj singh', 'available'),
  ('P028', 'Vimarsh', 'available'),
  ('P029', 'Sidharth singh', 'available'),
  ('P030', 'Tejas Suthar', 'available'),
  ('P031', 'Vikas mishra', 'available'),
  ('P032', 'Krishna', 'available'),
  ('P033', 'Sadashiv devadiga', 'available'),
  ('P034', 'Rakesh Singh', 'available'),
  ('P035', 'Shailesh Singh', 'available'),
  ('P036', 'Aryan Singh(602)', 'available'),
  ('P037', 'jeet shorey', 'available'),
  ('P038', 'Kush Dama', 'available'),
  ('P039', 'Veer dama', 'available'),
  ('P040', 'Ajay seth', 'available'),
  ('P041', 'Dinesh j suthar', 'available'),
  ('P042', 'Raj singh', 'available'),
  ('P043', 'Vadant kabra', 'available'),
  ('P044', 'Jeevan Gunjal', 'available'),
  ('P045', 'Deepak Yadav', 'available'),
  ('P046', 'Deep Dama', 'available'),
  ('P047', 'Kalash Porwal', 'available'),
  ('P048', 'AARUSH GUPTA BADA', 'available'),
  ('P049', 'Jimit', 'available'),
  ('P050', 'deepak dama', 'available'),
  ('P051', 'manoj mishra', 'available'),
  ('P052', 'Veer', 'available'),
  ('P053', 'Yuvraj Singh', 'available'),
  ('P054', 'Rishi Devadiga', 'available'),
  ('P055', 'Kailash Jain', 'available'),
  ('P056', 'Arpit ashish pandey', 'available'),
  ('P057', 'Rudhra Dev Jetli', 'available'),
  ('P058', 'Meet Dama', 'available'),
  ('P059', 'Sahil rastogi', 'available'),
  ('P060', 'Rounik singh', 'available'),
  ('P061', 'Anuj Doshi', 'available'),
  ('P062', 'Vansh suryawanshi', 'available'),
  ('P063', 'Nikhil Waghela', 'available'),
  ('P064', 'diinesh suthar', 'available'),
  ('P065', 'vivek mehra', 'available'),
  ('P066', 'jimmy mehta', 'available'),
  ('P067', 'jighnesh mehta', 'available'),
  ('P068', 'nilesh sharma', 'available'),
  ('P069', 'prakash kadam', 'available');
