-- SQL to insert all players from player_registrations.csv
-- Run this in Supabase SQL Editor after creating the players table

INSERT INTO players (player_id, player_name, status) VALUES
  ('P001', 'Lakshank Furiya', 'available'),
  ('P002', 'Kaushik yamber', 'available'),
  ('P003', 'Krishang bhardwaj', 'available'),
  ('P004', 'Aryan Singh(101)', 'available'),
  ('P005', 'Ashish R Pandey', 'available'),
  ('P006', 'Abhishek seth', 'available'),
  ('P007', 'Mitesh Mistry', 'available'),
  ('P008', 'Rupesh singh', 'available'),
  ('P009', 'Jatin', 'available'),
  ('P010', 'Nilesh Vishwakarma', 'available'),
  ('P011', 'Harish Jetli', 'available'),
  ('P012', 'Nikunj toshniwal', 'available'),
  ('P013', 'Parth Doshi', 'available'),
  ('P014', 'Mihir Makwana', 'available'),
  ('P015', 'Bharat mistry', 'available'),
  ('P016', 'Kishore', 'available'),
  ('P017', 'Aaryan mistry', 'available'),
  ('P018', 'Naveen Porwal', 'available'),
  ('P019', 'Prateek Gond', 'available'),
  ('P020', 'Hait Dama', 'available'),
  ('P021', 'Jay patel', 'available'),
  ('P022', 'Monish Shastri', 'available'),
  ('P023', 'Pramod Rane', 'available'),
  ('P024', 'SUNIL BOHRA', 'available'),
  ('P025', 'Viraj singh', 'available'),
  ('P026', 'aayan', 'available'),
  ('P027', 'Sidharth singh', 'available'),
  ('P028', 'Tejas Suthar', 'available'),
  ('P029', 'Vikas mishra', 'available'),
  ('P030', 'Kishan V', 'available'),
  ('P031', 'Sadashiv devadiga', 'available'),
  ('P032', 'Rakesh Singh', 'available'),
  ('P033', 'Shailesh Singh', 'available'),
  ('P034', 'Aryan Singh(602)', 'available'),
  ('P035', 'jeet shorey', 'available'),
  ('P036', 'Kush Dama', 'available'),
  ('P037', 'Veer dama', 'available'),
  ('P038', 'Ajay seth', 'available'),
  ('P039', 'Raj  singh', 'available'),
  ('P040', 'Jeevan Gunjal', 'available'),
  ('P041', 'Deep Dama', 'available'),
  ('P042', 'Kalash Porwal', 'available'),
  ('P043', 'deepak dama', 'available'),
  ('P044', 'manoj mishra', 'available'),
  ('P045', 'Yuvraj Singh', 'available'),
  ('P046', 'Rishi Devadiga', 'available'),
  ('P047', 'Kailash Jain', 'available'),
  ('P048', 'Meet Dama', 'available'),
  ('P049', 'Sahil rastogi', 'available'),
  ('P050', 'Rounik singh', 'available'),
  ('P051', 'Anuj Doshi', 'available'),
  ('P052', 'Nikhil Waghela', 'available'),
  ('P053', 'mahesh gaddam', 'available'),
  ('P054', 'amit mistry', 'available');
